name: "T-B uses-call test"
on:
  workflow_dispatch:
    inputs:
      only_sub_level:
        description: t
        required: false
        type: string
        default: ''
jobs:
  v66:
    if: ${{ inputs.only_sub_level == '' || inputs.only_sub_level == '66' }}
    uses: ./.github/workflows/fastbuild_5.10.66.yml
    with:
        ksu_type: ${{ inputs.ksu_type }}
        susfs_enable: ${{ inputs.susfs_enable }}
        kpm_enable: ${{ inputs.kpm_enable }}
        lz4_enable: ${{ inputs.lz4_enable }}
        lz4kd_enable: ${{ inputs.lz4kd_enable }}
        bbr_enable: ${{ inputs.bbr_enable }}
        better_net: ${{ inputs.better_net }}
        ssg_enable: ${{ inputs.ssg_enable }}
        rekernel_enable: ${{ inputs.rekernel_enable }}
        baseband_guard: ${{ inputs.baseband_guard }}
        ccache_update: ${{ inputs.ccache_update }}
        ccache_debug: ${{ inputs.ccache_debug }}
        kernel_suffix: ${{ inputs.kernel_suffix }}
    secrets: inherit