name: "T-K modC+perm"
on:
  workflow_call:
    inputs:
      t1:
        description: t
        required: false
        type: string
        default: ''
permissions:
  contents: write
jobs:
  e:
    runs-on: ubuntu-latest
    steps:
      - run: echo TK ok