name: "T-X2 call W2"
on:
  workflow_dispatch:
    inputs:
      ksu_type:
        description: t
        required: false
        type: string
        default: 'resukisu'
      susfs_enable:
        description: t
        required: false
        type: boolean
        default: true
      kpm_enable:
        description: t
        required: false
        type: boolean
        default: true
      lz4_enable:
        description: t
        required: false
        type: boolean
        default: true
      lz4kd_enable:
        description: t
        required: false
        type: boolean
        default: true
      bbr_enable:
        description: t
        required: false
        type: string
        default: 'false'
      better_net:
        description: t
        required: false
        type: boolean
        default: true
      ssg_enable:
        description: t
        required: false
        type: boolean
        default: true
      rekernel_enable:
        description: t
        required: false
        type: boolean
        default: true
      baseband_guard:
        description: t
        required: false
        type: boolean
        default: true
      ccache_update:
        description: t
        required: false
        type: boolean
        default: true
      ccache_debug:
        description: t
        required: false
        type: boolean
        default: true
      kernel_suffix:
        description: t
        required: false
        type: string
        default: ''
jobs:
  a:
    uses: ./.github/workflows/_t_w2.yml
    with:
        ksu_type: ${{ inputs.ksu_type }}
        susfs_enable: ${{ inputs.susfs_enable }}
        kpm_enable: ${{ inputs.kpm_enable }}
        lz4_enable: ${{ inputs.lz4_enable }}
        lz4kd_enable: ${{ inputs.lz4kd_enable }}
        bbr_enable: ${{ inputs.bbr_enable }}
        better_net: ${{ inputs.better_net }}
        ssg_enable: ${{ inputs.ssg_enable }}
        rekernel_enable: ${{ inputs.rekernel_enable }}
        baseband_guard: ${{ inputs.baseband_guard }}
        ccache_update: ${{ inputs.ccache_update }}
        ccache_debug: ${{ inputs.ccache_debug }}
        kernel_suffix: ${{ inputs.kernel_suffix }}
    secrets: inherit